// Generated by view binder compiler. Do not edit!
package com.example.progettomobile_07_05.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.progettomobile_07_05.R;
import com.google.android.material.card.MaterialCardView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class CardLayoutBinding implements ViewBinding {
  @NonNull
  private final MaterialCardView rootView;

  @NonNull
  public final TextView productDescriptionTextview;

  @NonNull
  public final ImageView productImageview;

  @NonNull
  public final TextView productNameTextview;

  @NonNull
  public final TextView productPositionTextview;

  @NonNull
  public final TextView productPriceTextview;

  @NonNull
  public final MaterialCardView singleCard;

  private CardLayoutBinding(@NonNull MaterialCardView rootView,
      @NonNull TextView productDescriptionTextview, @NonNull ImageView productImageview,
      @NonNull TextView productNameTextview, @NonNull TextView productPositionTextview,
      @NonNull TextView productPriceTextview, @NonNull MaterialCardView singleCard) {
    this.rootView = rootView;
    this.productDescriptionTextview = productDescriptionTextview;
    this.productImageview = productImageview;
    this.productNameTextview = productNameTextview;
    this.productPositionTextview = productPositionTextview;
    this.productPriceTextview = productPriceTextview;
    this.singleCard = singleCard;
  }

  @Override
  @NonNull
  public MaterialCardView getRoot() {
    return rootView;
  }

  @NonNull
  public static CardLayoutBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static CardLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.card_layout, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static CardLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.product_description_textview;
      TextView productDescriptionTextview = ViewBindings.findChildViewById(rootView, id);
      if (productDescriptionTextview == null) {
        break missingId;
      }

      id = R.id.product_imageview;
      ImageView productImageview = ViewBindings.findChildViewById(rootView, id);
      if (productImageview == null) {
        break missingId;
      }

      id = R.id.product_name_textview;
      TextView productNameTextview = ViewBindings.findChildViewById(rootView, id);
      if (productNameTextview == null) {
        break missingId;
      }

      id = R.id.product_position_textview;
      TextView productPositionTextview = ViewBindings.findChildViewById(rootView, id);
      if (productPositionTextview == null) {
        break missingId;
      }

      id = R.id.product_price_textview;
      TextView productPriceTextview = ViewBindings.findChildViewById(rootView, id);
      if (productPriceTextview == null) {
        break missingId;
      }

      MaterialCardView singleCard = (MaterialCardView) rootView;

      return new CardLayoutBinding((MaterialCardView) rootView, productDescriptionTextview,
          productImageview, productNameTextview, productPositionTextview, productPriceTextview,
          singleCard);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
