// Generated by view binder compiler. Do not edit!
package com.example.progettomobile_07_05.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.progettomobile_07_05.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentRegisterBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final EditText emailregister;

  @NonNull
  public final RelativeLayout fragmentRegister;

  @NonNull
  public final EditText nameregister;

  @NonNull
  public final EditText numbertelephoneregister;

  @NonNull
  public final EditText passwordregister;

  @NonNull
  public final Button registerbutton;

  @NonNull
  public final EditText repasswordregister;

  @NonNull
  public final TextView signuptitle;

  @NonNull
  public final EditText surnameregister;

  private FragmentRegisterBinding(@NonNull ScrollView rootView, @NonNull EditText emailregister,
      @NonNull RelativeLayout fragmentRegister, @NonNull EditText nameregister,
      @NonNull EditText numbertelephoneregister, @NonNull EditText passwordregister,
      @NonNull Button registerbutton, @NonNull EditText repasswordregister,
      @NonNull TextView signuptitle, @NonNull EditText surnameregister) {
    this.rootView = rootView;
    this.emailregister = emailregister;
    this.fragmentRegister = fragmentRegister;
    this.nameregister = nameregister;
    this.numbertelephoneregister = numbertelephoneregister;
    this.passwordregister = passwordregister;
    this.registerbutton = registerbutton;
    this.repasswordregister = repasswordregister;
    this.signuptitle = signuptitle;
    this.surnameregister = surnameregister;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentRegisterBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentRegisterBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_register, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentRegisterBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.emailregister;
      EditText emailregister = ViewBindings.findChildViewById(rootView, id);
      if (emailregister == null) {
        break missingId;
      }

      id = R.id.fragment_register;
      RelativeLayout fragmentRegister = ViewBindings.findChildViewById(rootView, id);
      if (fragmentRegister == null) {
        break missingId;
      }

      id = R.id.nameregister;
      EditText nameregister = ViewBindings.findChildViewById(rootView, id);
      if (nameregister == null) {
        break missingId;
      }

      id = R.id.numbertelephoneregister;
      EditText numbertelephoneregister = ViewBindings.findChildViewById(rootView, id);
      if (numbertelephoneregister == null) {
        break missingId;
      }

      id = R.id.passwordregister;
      EditText passwordregister = ViewBindings.findChildViewById(rootView, id);
      if (passwordregister == null) {
        break missingId;
      }

      id = R.id.registerbutton;
      Button registerbutton = ViewBindings.findChildViewById(rootView, id);
      if (registerbutton == null) {
        break missingId;
      }

      id = R.id.repasswordregister;
      EditText repasswordregister = ViewBindings.findChildViewById(rootView, id);
      if (repasswordregister == null) {
        break missingId;
      }

      id = R.id.signuptitle;
      TextView signuptitle = ViewBindings.findChildViewById(rootView, id);
      if (signuptitle == null) {
        break missingId;
      }

      id = R.id.surnameregister;
      EditText surnameregister = ViewBindings.findChildViewById(rootView, id);
      if (surnameregister == null) {
        break missingId;
      }

      return new FragmentRegisterBinding((ScrollView) rootView, emailregister, fragmentRegister,
          nameregister, numbertelephoneregister, passwordregister, registerbutton,
          repasswordregister, signuptitle, surnameregister);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
